Repository hashicorp/go-retryablehttp, pull requests merged in 2024-05, with the labels that each got.

#138 support HTTPDate in Retry-After header
  client.go
  client_test.go
Labels: enhancement

#155 Change URL from godoc to pkg.go.dev in README.md
  README.md
Labels: documentation

#197 Avoid reading all from bytes.Reader when get request body
  client.go
Labels: enhancement

#216 Re-sign request on retry
  client.go
  client_test.go
Labels: enhancement

#223 Changelog updates for #138, #197, #216
  CHANGELOG.md
Labels: documentation

#224 tooling: update go, unit test workflows, linting
  .github/workflows/go-retryablehttp.yml
  .github/workflows/pr-gofmt.yaml
  .github/workflows/pr-unit-tests-1.19.yaml
  .github/workflows/pr-unit-tests-1.20.yaml
  .go-version
  Makefile
  client.go
  client_test.go
  go.mod
  go.sum
Labels: dependencies, tooling

#210 Fix default retry policy for certificate verification errors and bad request headers
  cert_error_go119.go
  cert_error_go120.go
  client.go
  client_test.go
Labels: bug

#225 Changelog for #210, release v0.7.6
  CHANGELOG.md
Labels: documentation

#158 Redacted URL in logs / errors
  client.go
  client_test.go
Labels: logging
